- name: Check if fish is on list of shells
  shell: "grep $(which fish) /etc/shells"
  register: fish_in_shell
  failed_when: false

- name: Add fish to list of shell
  shell: "which fish >> /etc/shells"
  become: true
  when: fish_in_shell.rc == 1

- name: Get current user to change default shell
  shell: "whoami"
  register: current_user

- name: Make fish default shell
  become: true
  shell: "chsh -s $(which fish) {{ current_user.stdout }}"

- name: Install fisher
  shell: "fish -c 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher'"

- name: Remove plugin config file
  shell: "rm -f {{ ansible_env.HOME }}/.config/fish/fish_plugins"

- name: Remove fish config file
  shell: "rm -f {{ ansible_env.HOME }}/.config/fish/config.fish"

- name: Stow fish config
  shell: "stow --no-folding -v -t {{ ansible_env.HOME }} fish"
  args:
    chdir: "{{ ansible_env.PWD }}/dotfiles"

- name: Make local fish config file
  shell: "touch {{ ansible_env.HOME }}/.config/fish/local_config.fish"

- name: Install fish plugins
  shell: "fish -c 'fisher update'"
