brew_taps:
  - homebrew/cask-fonts

brew_packages:
  - fish
  - fd
  - fzf
  - git
  - neovim
  - stow
  - tmux

brew_casks:
  - bitwarden
  - dozer
  - firefox
  - font-mononoki-nerd-font
  - hammerspoon
  - iterm2
  - rectangle
  - unnaturalscrollwheels
