- name: Create system links for dotfiles
  hosts: localhost

  tasks:
    - name: Import iTerm settings
      shell: defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string {{ ansible_user_dir }}/dotfiles/iterm/