- name: Create system links for dotfiles
  hosts: localhost

  tasks:
    - name: Check if .config directory exists
      stat:
        path: "{{ ansible_user_dir }}/.config"
      register: config_dir

    - name: Backup existing .config directory
      command: mv "{{ ansible_user_dir }}/.config" "{{ ansible_user_dir }}/.config_bak"
      when: config_dir.stat.exists 

    - name: Create symbolic link for .config
      shell: ln -s "{{ playbook_dir }}/dotfiles/.config/" "{{ ansible_user_dir }}/.config/"