- name: "Configure Homebrew taps"
  homebrew_tap:
    name: "{{ item }}"
  loop: "{{ brew_taps }}"

- name: "Install Homebrew formulae"
  homebrew:
    path: /opt/homebrew
    name: "{{ item }}"
    state: latest
  loop: "{{ brew_packages }}"

- name: "Install Homebrew casks"
  homebrew_cask:
    path: /opt/homebrew
    name: "{{ item }}"
    state: latest
  loop: "{{ brew_casks }}"
